### ISSUE TITLE
Performance counters creation failed because of unauthorised access to registry key 'Global'

### ISSUE THREAD

**Issue by waheedsayed** [NimbusAPI/Nimbus#175]
I found a warning message in logs in regards to creating performance counters.
Message: _Could not create performance counter..._

Kindly, what is required to authorise Nimbus to create required performance counters?
Given that Nimbus is running from Azure Work Role.

Thanks

```stacktrace
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.UnauthorizedAccessException: Access to the registry key 'Global' is denied.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.InternalGetValue(String name, Object defaultValue, Boolean doNotExpand, Boolean checkSecurity)
   at Microsoft.Win32.RegistryKey.GetValue(String name)
   at System.Diagnostics.PerformanceMonitor.GetData(String item)
   at System.Diagnostics.PerformanceCounterLib.GetPerformanceData(String item)
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String category, String counter, Boolean& categoryExists)
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   at System.Diagnostics.PerformanceCounter.InitializeImpl()
   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName, Boolean readOnly)
   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName)
   at Nimbus.Infrastructure.Heartbeat.PerformanceCounters.System.PerProcessCpuUsage..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Nimbus.Infrastructure.Heartbeat.Heartbeat.<Start>d__d.MoveNext()

**Comment by waheedsayed** [comment]
I browsed the code base a little & It seems the reason is my worker role isn't running in elevated privilege (as the default) and/or I need to add Nimbus custom performance counters in my worker role definition. I'll give it a try soon & I'll update the issue (or hopefully close it)

**Comment by waheedsayed** [comment]
I found this comment in code:
// We're not running with admin privileges? Oh, well. No performance counter for you.

Well, this comment was going to be very useful if it was in the warning message :)
Therefore, I'll close the issue.
