### ISSUE TITLE
Nimbus occasionally using near 100% CPU in a thread

### ISSUE THREAD

**Issue by RobCentium** [NimbusAPI/Nimbus#218]
Every now and then I see a single thread using up nearly 100% of CPU, using Process Explorer this is what I see

![image](https://cloud.githubusercontent.com/assets/11070022/10010174/7d9850f4-612a-11e5-911c-7ecd321a1b05.png)

Just inspecting that thread using Process Explorer seems to reset it somehow and it goes back to functioning normally (literally, just opening up that threads screen and doing a stack trace, and the thread instantly stops hammering the CPU).

Any ideas as to what could be causing this?  The code itself seems fairly innocuous

```c#
protected override async Task<BrokeredMessage[]> FetchBatch(int batchSize, Task cancellationTask)
        {
            if (batchSize < 1) return new BrokeredMessage[0];

            try
            {
                var messageReceiver = await GetMessageReceiver();

                var receiveTask = messageReceiver.ReceiveBatchAsync(batchSize, TimeSpan.FromSeconds(300));
                await Task.WhenAny(receiveTask, cancellationTask);

                if (cancellationTask.IsCompleted) return new BrokeredMessage[0];
                
                var messages = await receiveTask;
                return messages.ToArray();
            }
            catch (MessagingEntityNotFoundException)
            {
                _queueManager.RemoveQueue(_queuePath);
                DiscardMessageReceiver();
                throw;
            }

            catch (Exception exc)
            {
                if (exc.IsTransientFault()) throw;
                DiscardMessageReceiver();
                throw;
            }
        }
```

**Comment by GiampaLab** [comment]
I just experienced the same behavior and the same piece of code was involved.
I agree It doesn't seem problematic but the caller method looks a better candidate:

```
private async Task Worker(Func<BrokeredMessage, Task> callback, Task cancellationTask)
        {
            while (_running)
            {
                try
                {
                    int workerThreads;
                    int completionPortThreads;
                    ThreadPool.GetMinThreads(out workerThreads, out completionPortThreads);
                    var batchSize = Math.Min(_throttle.CurrentCount, completionPortThreads);
                    var messages = await FetchBatch(batchSize, cancellationTask);
                    if (!_running) return;
                    if (messages.None()) continue;

                    GlobalMessageCounters.IncrementReceivedMessageCount(messages.Length);

                    var tasks = messages
                        .Select(m => Task.Run(async () =>
                                                    {
                                                        await _throttle.WaitAsync(_cancellationTokenSource.Token);
                                                        try
                                                        {
                                                            await callback(m);
                                                        }
                                                        finally
                                                        {
                                                            _throttle.Release();
                                                        }
                                                    }))
                        .ToArray();

                    if (_throttle.CurrentCount == 0) await Task.WhenAny(tasks);
                }
                catch (OperationCanceledException)
                {
                    // will be thrown when someone calls .Stop() on us
                }
                catch (Exception exc)
                {
                    _logger.Error(exc, "Worker exception in {0} for {1}", GetType().Name, this);
                }
            }
        }
```

This is a method of ThrottelingMessageReceiver class.
As you can see the FetchBatch method is called within a while loop. 
If it throws an exception the while loop will catch it(without throwing it) and will immediately retry.


The first exception we logged looks like:

```
Failed to close MessageSender instance before discarding it. - Microsoft.ServiceBus.Messaging.MessagingCommunicationException: The socket connection was aborted. This could be caused by an error processing your message or a receive timeout being exceeded by the remote host, or an underlying network resource issue. Local socket timeout was '00:00:00'. ---> System.ServiceModel.CommunicationException: The socket connection was aborted. This could be caused by an error processing your message or a receive timeout being exceeded by the remote host, or an underlying network resource issue. Local socket timeout was '00:00:00'. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.ServiceModel.Channels.SocketConnection.HandleSendAsyncCompleted()
   at System.ServiceModel.Channels.SocketConnection.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, Boolean immediate, TimeSpan timeout, WaitCallback callback, Object state)
   --- End of inner exception stack trace ---

Server stack trace: 
   at Microsoft.ServiceBus.Messaging.Channels.SharedChannel`1.CreateChannelAsyncResult.<GetAsyncSteps>d__7.MoveNext()
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.EnumerateSteps(CurrentThreadType state)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult.AsyncCompletionWrapperCallback(IAsyncResult result)

Exception rethrown at [0]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Channels.SharedChannel`1.OnEndCreateInstance(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.SingletonManager`1.EndGetInstance(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<GetAsyncSteps>b__2(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [1]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.RequestAsyncResult.<>c__DisplayClass17.<GetAsyncSteps>b__a(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [2]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<GetAsyncSteps>b__4(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [3]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.CloseOrAbortLinkAsyncResult.<GetAsyncSteps>b__6(CloseOrAbortLinkAsyncResult thisPtr, IAsyncResult a)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [4]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageSender.OnEndClose(IAsyncResult result)
   --- End of inner exception stack trace ---
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageSender.OnEndClose(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.MessageClientEntity.OnClose(TimeSpan timeout)
   at Microsoft.ServiceBus.Messaging.MessageClientEntity.Close(TimeSpan timeout)
   at Microsoft.ServiceBus.Messaging.MessageClientEntity.Close()
   at Nimbus.Infrastructure.MessageSendersAndReceivers.NimbusQueueMessageSender.DiscardMessageSender() in c:\projects\nimbus\src\Nimbus\Infrastructure\MessageSendersAndReceivers\NimbusQueueMessageSender.cs:line 58.
```

all the others are referring to the ThrottelingMessageReceiver class and its implementation NimbusSubscriptionMessageReceiver:
```
Worker exception in NimbusSubscriptionMessageReceiver for ReserveSwitchPorts/interxion.cloudinventory.service.switchpo220600648 - Microsoft.ServiceBus.Messaging.MessagingCommunicationException: The socket connection was aborted. This could be caused by an error processing your message or a receive timeout being exceeded by the remote host, or an underlying network resource issue. Local socket timeout was '00:00:00'. ---> System.ServiceModel.CommunicationException: The socket connection was aborted. This could be caused by an error processing your message or a receive timeout being exceeded by the remote host, or an underlying network resource issue. Local socket timeout was '00:00:00'. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.ServiceModel.Channels.SocketConnection.HandleSendAsyncCompleted()
   at System.ServiceModel.Channels.SocketConnection.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, Boolean immediate, TimeSpan timeout, WaitCallback callback, Object state)
   --- End of inner exception stack trace ---

Server stack trace: 
   at Microsoft.ServiceBus.Messaging.Channels.SharedChannel`1.CreateChannelAsyncResult.<GetAsyncSteps>d__7.MoveNext()
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.EnumerateSteps(CurrentThreadType state)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult.AsyncCompletionWrapperCallback(IAsyncResult result)

Exception rethrown at [0]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Channels.SharedChannel`1.OnEndCreateInstance(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.SingletonManager`1.EndGetInstance(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<GetAsyncSteps>b__2(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [1]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.RequestAsyncResult.<>c__DisplayClass17.<GetAsyncSteps>b__a(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [2]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<GetAsyncSteps>b__4(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [3]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver.EndReceiveCommand(IAsyncResult result, IEnumerable`1& messages)
   --- End of inner exception stack trace ---
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.RetryReceiveAsyncResult.TryReceiveEnd(IAsyncResult r, IEnumerable`1& messages)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.EndTryReceive(IAsyncResult result, IEnumerable`1& messages)
   at Microsoft.ServiceBus.Messaging.SubscriptionClient.EndReceiveBatch(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Nimbus.Infrastructure.MessageSendersAndReceivers.NimbusSubscriptionMessageReceiver.<FetchBatch>d__3.MoveNext() in c:\projects\nimbus\src\Nimbus\Infrastructure\MessageSendersAndReceivers\NimbusSubscriptionMessageReceiver.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Nimbus.Infrastructure.MessageSendersAndReceivers.ThrottlingMessageReceiver.<Worker>d__18.MoveNext() in c:\projects\nimbus\src\Nimbus\Infrastructure\MessageSendersAndReceivers\ThrottlingMessageReceiver.cs:line 94.
```

**Comment by RobCentium** [comment]
Hi Giampa,
I haven't unfortunately gotten any further with this, I still see it randomly every now and then.  In my case I don't see any exceptions logged like you do, but it could still be something to do with that while loop that is causing me issues.

Let me know if you figure anything out.

Rob

**Comment by taliesins** [comment]
I think the easiest way to tackle this is to provide an exponential retry algorithm in the while loop.

https://msdn.microsoft.com/en-us/library/dn589788.aspx

with at least a Thread.Yield but most likely a Thread.Sleep (booo) when exceptions do occur. It may be necessary to re-initialize the connection to service bus when this occurs as well.

Our exceptions seemed to coming from CommunicationException. I think this occurs when there is some network connectivity issues with service bus. I think it does not recover successfully and gets stuck in the while loop. 

This has happened at least twice, but we suspect it as one of the main reasons that we sometimes get services stuck at 100% cpu usage. To make thing interesting we even deploy a Seed Service project (cookie cutter pattern for our windows services) which contains nothing but a smoke test (a ping reply, so contains nothing that can go wrong) and we have seen that hit 100% cpu usage, so its related to infrastructure code.

**Comment by taliesins** [comment]
I think this may be a related error message:

```
Worker exception in NimbusSubscriptionMessageReceiver for SmokeTest/interxion.psmconnector.service.smoketesthandler - Microsoft.ServiceBus.Messaging.MessagingCommunicationException: The socket connection was aborted because an asynchronous send to the socket did not complete within the allotted timeout of 00:00:53.1248543. The time allotted to this operation may have been a portion of a longer timeout. ---> System.ServiceModel.CommunicationException: The socket connection was aborted because an asynchronous send to the socket did not complete within the allotted timeout of 00:00:53.1248543. The time allotted to this operation may have been a portion of a longer timeout. ---> System.ObjectDisposedException: The socket connection has been disposed.
Object name: 'System.ServiceModel.Channels.SocketConnection'.
   --- End of inner exception stack trace ---

Server stack trace: 
   at Microsoft.ServiceBus.Messaging.Channels.SharedChannel`1.CreateChannelAsyncResult.<GetAsyncSteps>d__7.MoveNext()
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.EnumerateSteps(CurrentThreadType state)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult.AsyncCompletionWrapperCallback(IAsyncResult result)

Exception rethrown at [0]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Channels.SharedChannel`1.OnEndCreateInstance(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.SingletonManager`1.EndGetInstance(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<GetAsyncSteps>b__2(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [1]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.RequestAsyncResult.<>c__DisplayClass17.<GetAsyncSteps>b__a(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [2]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Sbmp.RedirectBindingElement.RedirectContainerChannelFactory`1.RedirectContainerSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.RequestAsyncResult.<GetAsyncSteps>b__4(RequestAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

Exception rethrown at [3]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement.ReconnectChannelFactory`1.RequestSessionChannel.EndRequest(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver.EndReceiveCommand(IAsyncResult result, IEnumerable`1& messages)
   --- End of inner exception stack trace ---
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.RetryReceiveAsyncResult.TryReceiveEnd(IAsyncResult r, IEnumerable`1& messages)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.EndTryReceive(IAsyncResult result, IEnumerable`1& messages)
   at Microsoft.ServiceBus.Messaging.SubscriptionClient.EndReceiveBatch(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Nimbus.Infrastructure.MessageSendersAndReceivers.NimbusSubscriptionMessageReceiver.<FetchBatch>d__3.MoveNext() in c:\projects\nimbus\src\Nimbus\Infrastructure\MessageSendersAndReceivers\NimbusSubscriptionMessageReceiver.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Nimbus.Infrastructure.MessageSendersAndReceivers.ThrottlingMessageReceiver.<Worker>d__18.MoveNext() in c:\projects\nimbus\src\Nimbus\Infrastructure\MessageSendersAndReceivers\ThrottlingMessageReceiver.cs:line 94.
```

**Comment by uglybugger** [comment]
Hey all.. Thanks for following this up.

It's looking pretty strongly like it's the underlying communication channel that's faulting. We're doing some trickery in the registration of our MessagingFactory classes because they don't support telling us when they're faulted and they have no internal recovery. The later versions of the Azure SDK do do this but they're ASB-only; the only way we can tell that the WSB ones are broken is by reflecting over some private instance fields (which we do).

The `ThrottlingMessageReceiver` immediately retries on the `FetchBatch` call because it's expecting that method to acquire an instance of a functioning MessagingFactory from the pool. This would appear to not be happening.

One problem we face in identifying what goes wrong is that the way-too-general `MessagingException` is thrown for a whole bunch of different reasons, with sub-codes for some transient and some permanent faults. The stack traces above should help, so thank you :)

We're doing some major restructuring of the transport layers at the moment so I'm hoping to find and address this issue as part of that work.

**Comment by ma499** [comment]
In our case, we think we have a problem with `MessagingCommunicationException`. We see a few of these in our logs from time to time:

```
Failed to close MessageSender instance before discarding it. - Microsoft.ServiceBus.Messaging.MessagingCommunicationException: The socket connection was aborted. This could be caused by an error processing your message or a receive timeout being exceeded by the remote host, or an underlying network resource issue. Local socket timeout was '00:00:00'. ---> System.ServiceModel.CommunicationException: The socket connection was aborted. This could be caused by an error processing your message or a receive timeout being exceeded by the remote host, or an underlying network resource issue. Local socket timeout was '00:00:00'. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
at System.ServiceModel.Channels.SocketConnection.HandleSendAsyncCompleted()
at System.ServiceModel.Channels.SocketConnection.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, Boolean immediate, TimeSpan timeout, WaitCallback callback, Object state)
```

We tried to create a unit test to prove that a mock raising MessagingCommunicationException would  cause an infinite loop but failed. Curiously after ~10 iterations, the loop consistently exited. Stepping through in the Visual Studio debugger we found that on the final iteration, when exiting, the exception (re-)thrown by the FetchBatch method could not be parsed by the .NET framework, resulting in an exception from the GetType().Name expression. In the debugger We see the following:

`Unable to evaluate expression because the code is optimized or a native frame is on top of the call stack`
