### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by markalanevans** [NimbusAPI/Nimbus#237]
I have a very basic  app running, akin to the PizzaMaker Sample.

I'm able to process messages with it. (Publishing messages onto the bus via a (Customer) (Web controller) and then handling them with a Cashier (console app/Subscriber).

What seems odd, is that after the console app runs for a short time ~5min.

I start seeing these exceptions coming through:

```
2016-01-24 20:27:39 [Error] Worker exception in "WindowsServiceBusSubscriptionMe
ssageReceiver" for "t.coffeetalk.customer.messages.orderplacedevent/cashier.mark
evans4a32.cashierchargecustomerhandler"
System.NullReferenceException: Object reference not set to an instance of an obj
ect.
   at Nimbus.Transports.WindowsServiceBus.BrokeredMessages.BrokeredMessageFactor
y.<DeserializeNimbusMessage>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Nimbus.Transports.WindowsServiceBus.BrokeredMessages.BrokeredMessageFactor
y.<BuildNimbusMessage>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Nimbus.Transports.WindowsServiceBus.SendersAndRecievers.WindowsServiceBusS
ubscriptionMessageReceiver.<Fetch>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Nimbus.Infrastructure.MessageSendersAndReceivers.ThrottlingMessageReceiver
.<Worker>d__13.MoveNext()

```

The message i'm publishing to the bus is always valid: here is the code

```
public IHttpActionResult Get(int id)
        {

            Random random = new Random();
            int OrderId = random.Next(1, 100);
            var coffee = coffees.FirstOrDefault((p) => p.Id == id);
            
            if (coffee == null)
            {
                return NotFound();
            }
            coffee.Id = OrderId;


            _bus.Publish(new OrderPlacedEvent { OrderId = OrderId, Type = id.ToString() , Size = "Small" });
            System.Diagnostics.Debug.WriteLine("Have got your order {0}", OrderId.ToString());
            return Ok(coffee);
        }
```

Even more odd, is that sometimes I don't see the Cashier process the message, but there is no error on the controller.

I see that I currently have 45 messages in the deadletter office queue. Are they being stuck in there for some weird reason?

FYI: 
I'm connecting on my dev machine from both Customer & Cashier to an Azure Service bus.

What might causes this behavior?

**Comment by KodrAus** [comment]
Hmm, that's a bit strange. The error is occurring in this file: https://github.com/NimbusAPI/Nimbus/blob/e99743f343cd6ba6f1dd3e085f581082761a972a/src/Extensions/Nimbus.Transports.WindowsServiceBus/BrokeredMessages/BrokeredMessageFactory.cs#L101

It's trying to deserialise the message, but failing. What does your OrderPlacedEvent class look like? Are you able to inspect one of the deadletter queue and make sure all the data you expect is in them?
