### ISSUE TITLE
(v3) Transport.WSB issue on message handle failure

### ISSUE THREAD

**Issue by TheeJamesLee** [NimbusAPI/Nimbus#251]
Hi,
Using 3.0.0.564 from the MyGet feed with a "IHandleCompetingEvent" handler, WSB Transport, ASB connection string, when a message is being handled Nimbus fails to re-queue the message.

At this point on the ServiceBus namespace there are input queues for the publisher and subscriber instances, as well as a topic (t.#####) with a subscriber for the actual handler, which actually process the event.

On failure, there are attempts at 2 network calls returning a 409 Conflict and 400 Bad Request from ASB.  The gist of the request is that it looks like Nimbus is trying to create a 'queue' with the same name as the 'topic' that generates the 409 Conflict and the ultimate failure to re-enqueue the message exception.

**Comment by TheeJamesLee** [comment]
Hi,
I've just had a chance to get a full stack trace for the issue.  I've tried going through the code this morning to see if I could spot it, but no luck yet.  I was looking for a point where the handler looks to re queue the message and decides if the event should be placed on a queue or a topic.  My understanding is that until it is actually dead lettered it would go back to the same location - ie, the topic.

> 2016-05-04 07:16:27 [Warning] Dispatch failed for message 7876b657-72cd-4e67-a5a5-30621237c6c5
Nimbus.Exceptions.DispatchFailedException: Failed to dispatch EventMessage ---> System.Exception: Dummy
   at XXX.Handle(XXX busEvent) in XXXHandler.cs:line 27
   at Nimbus.Infrastructure.Events.CompetingEventMessageDispatcher.DispatchToHandleMethod[TBusEvent](TBusEvent busEvent, Object handler)
   at Nimbus.Infrastructure.Events.EventMessageDispatcher.<Dispatch>d__8`1.MoveNext()
   --- End of inner exception stack trace ---
   at Nimbus.Infrastructure.Events.EventMessageDispatcher.<Dispatch>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nimbus.Infrastructure.Events.EventMessageDispatcher.<Dispatch>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nimbus.Infrastructure.MessagePump.<Dispatch>d__15.MoveNext()
2016-05-04 07:16:28 [Warning] A transient failure occurred in action "Creating queue t.XXX".
System.ArgumentException: The remote server returned an error: (400) Bad Request. SubCode=40000. Bad Request. TrackingId:69612ace-7e21-48e2-9c00-404e2905fedd_G60,TimeStamp:5/4/2016 6:16:34 AM ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.ServiceBusResourceOperations.CreateOrUpdateAsyncResult`1.<GetAsyncSteps>b__14(CreateOrUpdateAsyncResult`1 thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
   --- End of inner exception stack trace ---

> Server stack trace:


> Exception rethrown at [0]:
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.NamespaceManager.CreateOrUpdateQueueAsyncResult.CreateDescription(CreateOrUpdateQueueAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.NamespaceManager.CreateOrUpdateQueueAsyncResult.<GetAsyncSteps>b__9c(CreateOrUpdateQueueAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

> Exception rethrown at [1]:
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Nimbus.Transports.WindowsServiceBus.QueueManagement.AzureQueueManager.<>c__DisplayClass30_0.<EnsureQueueExists>b__0()
   at Nimbus.Infrastructure.Retries.Retry.Do(Action action, String actionName)
2016-05-04 07:16:29 [Warning] A transient failure occurred in action "Creating queue t.XXX".
System.ArgumentException: The remote server returned an error: (400) Bad Request. SubCode=40000. Bad Request. TrackingId:fb96c2a6-eeaf-4e63-b0a1-7faf80c15d38_G60,TimeStamp:5/4/2016 6:16:35 AM ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.ServiceBusResourceOperations.CreateOrUpdateAsyncResult`1.<GetAsyncSteps>b__14(CreateOrUpdateAsyncResult`1 thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
   --- End of inner exception stack trace ---

> Server stack trace:


> Exception rethrown at [0]:
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.NamespaceManager.CreateOrUpdateQueueAsyncResult.CreateDescription(CreateOrUpdateQueueAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.NamespaceManager.CreateOrUpdateQueueAsyncResult.<GetAsyncSteps>b__9c(CreateOrUpdateQueueAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

> Exception rethrown at [1]:
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Nimbus.Transports.WindowsServiceBus.QueueManagement.AzureQueueManager.<>c__DisplayClass30_0.<EnsureQueueExists>b__0()
   at Nimbus.Infrastructure.Retries.Retry.Do(Action action, String actionName)
2016-05-04 07:16:32 [Warning] A transient failure occurred in action "Creating queue t.XXX".
System.ArgumentException: The remote server returned an error: (400) Bad Request. SubCode=40000. Bad Request. TrackingId:88aedc80-af6f-492f-9c5f-7b577582bf41_G60,TimeStamp:5/4/2016 6:16:38 AM ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.ServiceBusResourceOperations.CreateOrUpdateAsyncResult`1.<GetAsyncSteps>b__14(CreateOrUpdateAsyncResult`1 thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
   --- End of inner exception stack trace ---

> Server stack trace:


> Exception rethrown at [0]:
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.NamespaceManager.CreateOrUpdateQueueAsyncResult.CreateDescription(CreateOrUpdateQueueAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.NamespaceManager.CreateOrUpdateQueueAsyncResult.<GetAsyncSteps>b__9c(CreateOrUpdateQueueAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

> Exception rethrown at [1]:
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Nimbus.Transports.WindowsServiceBus.QueueManagement.AzureQueueManager.<>c__DisplayClass30_0.<EnsureQueueExists>b__0()
   at Nimbus.Infrastructure.Retries.Retry.Do(Action action, String actionName)
2016-05-04 07:16:35 [Warning] A transient failure occurred in action "Creating queue t.XXX".
System.ArgumentException: The remote server returned an error: (400) Bad Request. SubCode=40000. Bad Request. TrackingId:e796d1b6-4a10-490d-9b86-7435eb84b155_G60,TimeStamp:5/4/2016 6:16:41 AM ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.ServiceBusResourceOperations.CreateOrUpdateAsyncResult`1.<GetAsyncSteps>b__14(CreateOrUpdateAsyncResult`1 thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
   --- End of inner exception stack trace ---

> Server stack trace:


> Exception rethrown at [0]:
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.NamespaceManager.CreateOrUpdateQueueAsyncResult.CreateDescription(CreateOrUpdateQueueAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.NamespaceManager.CreateOrUpdateQueueAsyncResult.<GetAsyncSteps>b__9c(CreateOrUpdateQueueAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

> Exception rethrown at [1]:
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Nimbus.Transports.WindowsServiceBus.QueueManagement.AzureQueueManager.<>c__DisplayClass30_0.<EnsureQueueExists>b__0()
   at Nimbus.Infrastructure.Retries.Retry.Do(Action action, String actionName)
2016-05-04 07:16:39 [Error] A permanent failure occurred in action "Creating queue t.XXX".
System.ArgumentException: The remote server returned an error: (400) Bad Request. SubCode=40000. Bad Request. TrackingId:a8214b9b-2776-4015-8613-81bfa7d1ed06_G60,TimeStamp:5/4/2016 6:16:46 AM ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.ServiceBusResourceOperations.CreateOrUpdateAsyncResult`1.<GetAsyncSteps>b__14(CreateOrUpdateAsyncResult`1 thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
   --- End of inner exception stack trace ---

> Server stack trace:


> Exception rethrown at [0]:
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.NamespaceManager.CreateOrUpdateQueueAsyncResult.CreateDescription(CreateOrUpdateQueueAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.NamespaceManager.CreateOrUpdateQueueAsyncResult.<GetAsyncSteps>b__9c(CreateOrUpdateQueueAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

> Exception rethrown at [1]:
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Nimbus.Transports.WindowsServiceBus.QueueManagement.AzureQueueManager.<>c__DisplayClass30_0.<EnsureQueueExists>b__0()
   at Nimbus.Infrastructure.Retries.Retry.Do(Action action, String actionName)
2016-05-04 07:16:39 [Error] Failed to re-enqueue message 7876b657-72cd-4e67-a5a5-30621237c6c5 for re-delivery.
System.ArgumentException: The remote server returned an error: (400) Bad Request. SubCode=40000. Bad Request. TrackingId:a8214b9b-2776-4015-8613-81bfa7d1ed06_G60,TimeStamp:5/4/2016 6:16:46 AM ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.ServiceBusResourceOperations.CreateOrUpdateAsyncResult`1.<GetAsyncSteps>b__14(CreateOrUpdateAsyncResult`1 thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
   --- End of inner exception stack trace ---

> Server stack trace:


> Exception rethrown at [0]:
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.NamespaceManager.CreateOrUpdateQueueAsyncResult.CreateDescription(CreateOrUpdateQueueAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.NamespaceManager.CreateOrUpdateQueueAsyncResult.<GetAsyncSteps>b__9c(CreateOrUpdateQueueAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

> Exception rethrown at [1]:
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Nimbus.Transports.WindowsServiceBus.QueueManagement.AzureQueueManager.<>c__DisplayClass30_0.<EnsureQueueExists>b__0()
   at Nimbus.Infrastructure.Retries.Retry.Do(Action action, String actionName)
   at Nimbus.Transports.WindowsServiceBus.QueueManagement.AzureQueueManager.EnsureQueueExists(String queuePath)
   at Nimbus.Transports.WindowsServiceBus.QueueManagement.AzureQueueManager.<>c__DisplayClass15_0.<<CreateMessageSender>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nimbus.Transports.WindowsServiceBus.DelayedDelivery.DelayedDeliveryService.<DeliverAfter>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Nimbus.Infrastructure.MessagePump.<Dispatch>d__15.MoveNext()
