### ISSUE TITLE
MessageLoggingExtensions throws exception on formatting output on any ILogger implementation

### ISSUE THREAD

**Issue by bjoka042** [NimbusAPI/Nimbus#268]
logger.Debug("{DispatchAction} message to {To} ({Elapsed})",
                         dispatchAction,
                         queueOrTopicPath,
                         elapsed);

This doesnt work for me. Should it not be:

 logger.Debug("{0} message to {1} ({2})",
                         dispatchAction,
                         queueOrTopicPath,
                         elapsed);

**Comment by DamianMac** [comment]
Sorry @bjoka042 I'm not sure I understand, what do you mean it doesn't work?

**Comment by bjoka042** [comment]
What version of c# is this code ment to run with?

When i try to log with for example TraceLogger it throws errors on formatting the output.

{"Input string was not in a correct format."}

   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at System.Diagnostics.TraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String format, Object[] args)
   at System.Diagnostics.TraceInternal.TraceEvent(TraceEventType eventType, Int32 id, String format, Object[] args)
   at Nimbus.Infrastructure.Logging.TraceLogger.Error(Exception exc, String format, Object[] args)
   at Nimbus.Infrastructure.Logging.MessageLoggingExtensions.LogDispatchError(ILogger logger, String dispatchAction, String queueOrTopicPath, TimeSpan elapsed, Exception exception)
   at Nimbus.Infrastructure.Commands.BusCommandSender.<Deliver>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

How would the string.format be able to format the input string with names like {queueOrTopicPath}?
