### ISSUE TITLE
BatchingMessageSender failing to retry messages

### ISSUE THREAD

**Issue by michaelnoonan** [NimbusAPI/Nimbus#96]
It looks for all the world like the BrokeredMessage has already been consumed in the process of being sent and triggers the Environment.FailFast() circuit breaker.

```
2014-06-17 10:51:49.065 +10:00 [Warning] Going to retry after "MessagingCommunicationException" was thrown sending batch: "Could not connect to net.tcp://mynamespace.servicebus.windows.net:9354/. The connection attempt lasted for a time span of 00:00:00. TCP error code 10013: An attempt was made to access a socket in a way forbidden by its access permissions 111.221.80.244:9354. "
2014-06-17 10:51:49.065 +10:00 [Debug] Flushing outbound message queue "appserver.requests" (1 messages)
2014-06-17 10:51:49.066 +10:00 [Error] FATAL: The BatchingMessageSender has failed and cannot be recovered: "The operation cannot be performed because the brokered message 'dc97164e202049359f1adfc2abe25bd4' has already been consumed. Please use a new BrokeredMessage instance for the operation."
System.InvalidOperationException: The operation cannot be performed because the brokered message 'dc97164e202049359f1adfc2abe25bd4' has already been consumed. Please use a new BrokeredMessage instance for the operation.
   at Microsoft.ServiceBus.Messaging.MessagingUtilities.ValidateAndSetConsumedMessages(IEnumerable`1 messages)
   at Microsoft.ServiceBus.Messaging.MessageSender.Send(TrackingContext trackingContext, IEnumerable`1 messages, TimeSpan timeout)
   at Nimbus.Infrastructure.MessageSendersAndReceivers.NimbusQueueMessageSender.SendBatch(BrokeredMessage[] toSend)
   at Nimbus.Infrastructure.MessageSendersAndReceivers.BatchingMessageSender.FlushMessages()
```

I tried changing the retry to logic so it clones the message before it is enqueued for a retry, but this fails with the following exception.
```c#
_logger.Warn("Going to retry after {0} was thrown sending batch: {1}", ex.GetType().Name, ex.Message);
lock (_outboundQueue)
{
    _outboundQueue.AddRange(toSend.Select(m => m.Clone()));
}
```

```
System.UnauthorizedAccessException: MemoryStream's internal buffer cannot be accessed.
   at System.IO.MemoryStream.GetBuffer()
   at Microsoft.ServiceBus.Messaging.BrokeredMessage.CloneStream(Stream originalStream, Boolean canThrowException)
   at Microsoft.ServiceBus.Messaging.BrokeredMessage..ctor(BrokeredMessage originalMessage, Boolean clientSideCloning)
   at Microsoft.ServiceBus.Messaging.BrokeredMessage.Clone(Boolean includeSystemProperties)
   at Microsoft.ServiceBus.Messaging.BrokeredMessage.Clone()
   at Nimbus.Infrastructure.MessageSendersAndReceivers.BatchingMessageSender.<FlushMessages>b__b(BrokeredMessage m) in c:\readify\Centium\NextGen\Nimbus\src\Nimbus\Infrastructure\MessageSendersAndReceivers\BatchingMessageSender.cs:line 73
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at Nimbus.Infrastructure.MessageSendersAndReceivers.BatchingMessageSender.FlushMessages() in c:\readify\Centium\NextGen\Nimbus\src\Nimbus\Infrastructure\MessageSendersAndReceivers\BatchingMessageSender.cs:line 73
   at Nimbus.Infrastructure.MessageSendersAndReceivers.BatchingMessageSender.<TriggerMessageFlush>b__6() in c:\readify\Centium\NextGen\Nimbus\src\Nimbus\Infrastructure\MessageSendersAndReceivers\BatchingMessageSender.cs:line 39
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**I'm not sure what value we're actually getting by implementing retry logic since the ServiceBus MessageSender classes already implement a retry policy by default.**

**Comment by drewfreyling** [comment]
Any idea on when that is happening?
