### ISSUE TITLE
Nimbus doesn't support AMQP - Batching operations

### ISSUE THREAD

**Issue by michaelnoonan** [NimbusAPI/Nimbus#99]
Changing the connection string to specify `TransportType=Amqp` yields the following exception trying to receive messages:

```
System.NotSupportedException: The feature 'ReceiveBatch' is not supported with the current configuration.

Server stack trace: 
   at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessageReceiver.OnBeginTryReceive(TrackingContext trackingContext, Int32 messageCount, TimeSpan serverWaitTime, AsyncCallback callback, Object state)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.RetryReceiveAsyncResult.<GetAsyncSteps>b__62(RetryReceiveAsyncResult thisPtr, TimeSpan t, AsyncCallback c, Object s)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.EnumerateSteps(CurrentThreadType state)

Exception rethrown at [0]: 
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.RetryReceiveAsyncResult.TryReceiveEnd(IAsyncResult r, IEnumerable`1& messages)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.EndTryReceive(IAsyncResult result, IEnumerable`1& messages)
   at Microsoft.ServiceBus.Messaging.MessageReceiver.EndReceiveBatch(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Nimbus.Infrastructure.MessageSendersAndReceivers.NimbusQueueMessageReceiver.<FetchBatch>d__3.MoveNext() in src\Nimbus\Infrastructure\MessageSendersAndReceivers\NimbusQueueMessageReceiver.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Nimbus.Infrastructure.MessageSendersAndReceivers.NimbusMessageReceiver.<Worker>d__15.MoveNext() in src\Nimbus\Infrastructure\MessageSendersAndReceivers\NimbusMessageReceiver.cs:line 67
```

This is also potentially true of `BatchSend()`.

**Comment by drewfreyling** [comment]
Is this working in v3?

**Comment by iamsoorya** [comment]
Is v3 licensed or open source. I want to know do I upgrade to v3?

**Comment by iamsoorya** [comment]
Dear Sir,

I am a solution architect and working for TCS India. We have  a new project
for client and I want recommend the Nimbus 3.x for a solution based on
Azure Service Bus.

My question is : Why is Nimbus based on .NET 4.5 why not 4.6 or 4.7 version?

Second question I have is, are you going to make it available for .NET
standard 2.0?

-- 
Kind Regards
Sooryanarayan Hegde

**Comment by todthomson** [comment]
@iamsoorya Take a look at:

**Comment by iamsoorya** [comment]
Why is source code targetting 4.5 why not 4.6.1.


On Thu, 5 Oct 2017 at 12:04 PM, Sooryanarayan Hegde <iamsoorya@gmail.com>
wrote:

> Dear Sir,
>
> I am a solution architect and working for TCS India. We have  a new
> project for client and I want recommend the Nimbus 3.x for a solution based
> on Azure Service Bus.
>
> My question is : Why is Nimbus based on .NET 4.5 why not 4.6 or 4.7
> version?
>
> Second question I have is, are you going to make it available for .NET
> standard 2.0?
>
> --
> Kind Regards
> Sooryanarayan Hegde
>
-- 
Kind Regards
Sooryanarayan Hegde
